@env = local
@token = eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFuZ2lla2F0ZXJpbmUwNTA2QGdtYWlsLmNvbSIsIm5hbWUiOiJDYXJsb3MiLCJyb2xlIjoiUk9MRV9IVUVTUEVEIiwic3ViIjoiNiIsImlhdCI6MTc2MDIyMzUxOSwiZXhwIjoxNzYwMjI3MTE5fQ.waSxsZSHf9ChhnN-7ife9l_4Gl_ZE6H1w_F8YfHTPzQ

### Hacer un comentario
POST http://localhost:8080/api/comentarios/2
Authorization: Bearer {{token}}
content-type: application/json

{
  "texto": "Excelente alojamiento",
  "calificacion": "4",
  "idAlojamiento" : 1
}

### Listar comentarios por alojamiento
GET http://localhost:8080/api/comentarios/alojamiento/1
Authorization: Bearer {{token}}