@env = local
@token = eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InNvZmlhQGVtaWFsLmNvbSIsIm5hbWUiOiJTb2ZpYSIsInJvbGUiOiJST0xFX0FORklUUklPTiIsInN1YiI6IjUiLCJpYXQiOjE3NjI2NjQ4NzcsImV4cCI6MTc2MjY2ODQ3N30.QK_O0RABmFAeLJYhZfS_nlB8inj-DH7ndm6sh8FakBg

### Responder un comentario (solo rol ANFITRION)
POST http://localhost:8080/api/respuestas
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "respuesta": "No concuerdo, pero bueno, no todos pueden tener buenos gustos",
  "idComentario": 2
}

### Obtener todas la respuesta por comentario (rol ANFITRION o HUESPED)
GET http://localhost:8080/api/respuestas/comentario/2
Authorization: Bearer {{token}}

### Obtener una respuesta por id (rol ANFITRION o HUESPED)
GET http://localhost:8080/api/respuestas/2
Authorization: Bearer {{token}}
