@env = local
@token = eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InNvZmlhQGVtaWFsLmNvbSIsIm5hbWUiOiJTb2ZpYSIsInJvbGUiOiJST0xFX0FORklUUklPTiIsInN1YiI6IjUiLCJpYXQiOjE3NjI2NTYzMTEsImV4cCI6MTc2MjY1OTkxMX0.qU1whE5Je9L3eIIVkSTgWM3f6kWTs76VOK2mhjoMkZs
//el token se obtiene del login, luego se puede copiar y pegar aquí para usar en las demás peticiones.

### Crear un usuario
POST http://localhost:8080/api/auth/register
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nombre"

Celeste
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="telefono"

3207794581
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

cel@email.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

Cc123123
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="fechaNacimiento"

2007-11-22
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="fotoUrl"; filename="foto.jpg"
Content-Type: image/jpeg

< ./foto-test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Crear un usuario - anfitrión
POST http://localhost:8080/api/auth/register
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nombre"

Sofia
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="telefono"

3207548156
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

sofia@emial.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

Sofia123
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="fechaNacimiento"

2002-10-22
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="fotoUrl"; filename="foto.jpg"
Content-Type: image/jpeg

< ./foto-test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Login para obtener el token JWT
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "cel@email.com",
  "password": "Cc123123"
}

### Obtener todos los usuarios (requiere token)
GET http://localhost:8080/api/usuario
Authorization: Bearer {{token}}

### Obtener un usuario por id (cambie "id" por el id del usuario que desea obtener)
GET http://localhost:8080/api/usuario/4
Authorization: Bearer {{token}}

### Actualizar un usuario (cambie "id" por el id del usuario que desea actualizar)
PUT http://localhost:8080/api/usuario/4
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nombre"

Celeste
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="telefono"

3207794581
------WebKitFormBoundary7MA4YWxkTrZu0gW

null
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Se olvidó la contraseña
POST http://localhost:8080/api/auth/forgot-password
Content-Type: application/json

{
  "email": "cel@email.com"
}

### Resetear la contraseña (se pega el codigo de verificación que llega al correo)
PUT  http://localhost:8080/api/auth/reset-password
Content-Type: application/json

{
  "email": "cel@email.com",
  "verificationCode": "689077",
  "newPassword": "Cc123124"
}

### Cambiar la contraseña actual por una nueva (requiere autenticación)
PUT http://localhost:8080/api/usuario/4/cambiar-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "Cc123124",
  "newPassword": "Cc123123"
}

### Eliminar un usuario (cambie "id" por el id del usuario que desea eliminar)
DELETE http://localhost:8080/api/usuario/1
Authorization: Bearer {{token}}